- docs/conf.py
- ladybug_rhino/bakeobjects.py
- ladybug_rhino/fromobjects.py
- ladybug_rhino/grasshopper.py
- ladybug_rhino/intersect.py
- ladybug_rhino/text.py
Hi @chriswmackey,
I did some research and found a way to ignore libraries that can not be found in the build process. You can use the `autodoc_mock_imports` config value in the config.py file with the list of libraries you want sphinx to ignore (or rather create mock imports of). For future reference, only this has to include top-level modules, I noticed submodules will be ignored.
I added also for your review the changes to the docstrings, these were minimal and pretty straightforward.
> Format docstrings for correct display in sphinx-generated bootstrap pages

- ladybug_rhino/grasshopper.py
It was converting other iterables like colors the way that it was currently written.
> fix(grasshopper): Correct to_data_tree to only convert lists and tuples

- ladybug_rhino/colorize.py
- ladybug_rhino/planarize.py
- ladybug_rhino/togeometry.py
This commit adds another method to the planarize module to planarize curved solids in a way that preserves their solidity.
This method gets used in the to_polyface translator and will be used to make a new honeybee-grasshooper-core planarization component.
This PR also includes a colorize module to produce colored points but it's not being used at the moment.
> feat(planarize) Improve planarization of closed solids

- ladybug_rhino/config.py
I realized that all of the grasshopper components were treating the angle tolerance as a value in degrees and not radians. This commit fixes this issue.
> fix(config): Ensure angle_tolerance is in degrees

- ladybug_rhino/config.py
- ladybug_rhino/fromobjects.py
- ladybug_rhino/grasshopper.py
- ladybug_rhino/intersect.py
- ladybug_rhino/planarize.py
- ladybug_rhino/togeometry.py
It turns out that meshing each and every solid Brep to get vertices creates a lot of problems. It seems better to use our old method and, if people need to planarize curved geometry, they can use the dedicated planarization component.
I also fixed a bunch of typos across the library.
> fix(to_polyface): Use older method for planarization

- ladybug_rhino/pythonpath.py
This was causing failures in the Mac installation pathway.
> fix(pythonpath): Fix command to copy libraries

- ladybug_rhino/grasshopper.py
Resolves https://github.com/ladybug-tools/ladybug-grasshopper/issues/33
> fix(grasshopper): Add methods to hide and show component outputs

- ladybug_rhino/fromgeometry.py
This way, it will be easier to debug when invalid geometry is input.
> fix(fromgeometry): Catch the case of illegal model geometry

- ladybug_rhino/cli/__init__.py
- ladybug_rhino/pythonpath.py
This commit updates the set-python-search command to work for both Rhino 6 and Rhino 7.  The command is smart enough to sense what is installed and just set the path for that.
Right now, the process of setting the path for Rhino 7 is the same as it is for Rhino 6, including the copying of files to the scripts folder on Mac.  If McNeel adds a better way to do it, we can switch to that.
@mostaphaRoudsari and @MingboPeng , I just wanted you to be aware of this change as this means that we should be able to start having people beta test the Grasshopper plugin with Rhino 7.
> feat(pythonpath): Ensure IronPython path is set for Rhino 7 if instaled

- ladybug_rhino/pythonpath.py
The location of the Application Data directory will vary on different
installations or group policies. Rather than hard-coding, we should use
the environment variable `%APPDATA%` on Windows installs.
> Fixes Application Data directory on Windows

- ladybug_rhino/grasshopper.py
- ladybug_rhino/versioning/__init__.py
- ladybug_rhino/versioning/component.py
- ladybug_rhino/versioning/export.py
- ladybug_rhino/versioning/gather.py
- ladybug_rhino/versioning/userobject.py
- ladybug_rhino/viewport.py
After we have copay/pasted these functions so many times, it was about time that we put them into a re-usable library.  The versioning sub-package houses modules to search for components by plugin on the canvas, create user objects, check user object versions, and export JSONs.
> feat(versioing): Add versioning subpackage for plugin maintenance

- ladybug_rhino/versioning/diff.py
- ladybug_rhino/versioning/export.py
- ladybug_rhino/versioning/gather.py
- ladybug_rhino/versioning/userobject.py
This organization seems a lot cleaner to me even though I know it mixes some of the functions used to check versions before export with the functions that check versions for syncing Grasshopper files.
The good news is that, in the process, I have definitely removed some redundant code and made it so that we have one good method for checking something rather than 2 slightly different copies of it.
> feat(diff): Put all functions that evaluate differences in one module

- ladybug_rhino/versioning/diff.py
I did several tests and it looks like there shouldn't be any issues setting the type hint, item/list access, or the name change of an input or an output.
Now, the only thing that needs to be manually replaced is the case where the number of inputs or outputs have changed.
> feat(versioning): Have sync component update inputs + outputs

- ladybug_rhino/fromgeometry.py
- ladybug_rhino/planarize.py
- ladybug_rhino/togeometry.py
It seems that it's possible to have a Brep where the object doesn't have duplicate vertices but the loops of the Brep's faces have them.  So this commit adds an extra check to remove such duplicate vertices.
I am also updating the polyface translators to used the more robust meshing translation whenever the input Brep has a curved face since this should help preserve solidity in more cases of using the default components without the "Planarize Brep" component.
Lastly, I am changing some of the methods so that I can remove the RhinoCommon import statement in the "Planarize Brep" component.
> fix(geometry): Add extra check for duplicate vertices

- ladybug_rhino/pythonpath.py
This should ensure that the python path gets correctly set for all of the user's Rhino.Inside python paths.
> fix(pythonpath): Search for all settings-Scheme files

- ladybug_rhino/fromgeometry.py
HI @chriswmackey,
HB Color Face Attributes component only outputs the curve for the boundary. This PR fixes it so that the component outputs curves for hole as well when a face has holes.
This will require `extend` instead of `append`  on [this](https://github.com/ladybug-tools/honeybee-grasshopper-core/blob/master/honeybee_grasshopper_core/src/HB%20Color%20Face%20Attributes.py#L90) line.
> fix(fromgeometry) : Add hole curves along with boundary curve

- ladybug_rhino/togeometry.py
While Rhino has robust checks that prevent most Breps from having 0 area, the same can't really be said for meshes. So I'm adding a zero-area for the mesh case just to be sure. It has a negligible effect on the run-time since we're already computing the area to ensure the vertices are counter-clockwise.
> fix(togeometry): Catch the case of zero-area mesh faces

- ladybug_rhino/pythonpath.py
This will ensure that, for the Mac installation, the recipe packages will get copied to and cleaned out of the Rhino scripts folder as expected.
> fix(pythonpath): Add packages for recipes

- ladybug_rhino/ghpath.py
- ladybug_rhino/pythonpath.py
It seems that the location where user objects are copied on Mac is different for each version of Rhino. So, we have to make sure that we copy it to all of them.
> fix(ghpath): Fix the copying of user objects on Mac

- .gitignore
- ladybug_rhino/intersect.py
Hi @chriswmackey 
we can try in this way. It gives you an` Empty Array `when the intersection fails because of the ironpython/python truth values.
> fix(intersection.py): Replace the intersection if else statement

- ladybug_rhino/viewport.py
This way, if someone tries to get a NamedView that isn't open, we can still get it.
> fix(viewport): Restore ViewPorts if they are not open

- ladybug_rhino/fromgeometry.py
If we use ladybug_geometry's built-in triangulation methods to get the mesh, this will allow us to preview geometries with holes better.
> fix(fromgeometry): Implement more robust way to get colored meshes

- ladybug_rhino/togeometry.py
More info is here:
https://discourse.ladybug.tools/t/input-geo-is-not-a-closed-volume/13488/31?u=trevorfedyna
> fix(togeometry): Rejoin Breps when cleaning planarized versions

- ladybug_rhino/versioning/userobject.py
This is needed now that we are storing the user objects in Program Files.
> fix(userobject): Handle the case that access to Program Files is denied

- ladybug_rhino/bakeobjects.py
- ladybug_rhino/preview.py
This commit also adds the GUIDs of geometry objects to baked AnalysisGeometries so that the Rhino plugin can pick them up.
> fix(visualization): Perform unit conversions for Vis Set units

- ladybug_rhino/bakeobjects.py
- ladybug_rhino/visset.py
This should prevent possible errors when Grasshopper is not yet loaded.
> fix(visset): Move Bake-able VisualizationSet to its own module

- ladybug_rhino/bakedisplay.py
- ladybug_rhino/bakegeometry.py
- ladybug_rhino/bakeobjects.py
- ladybug_rhino/light.py
We currently get the active doc once when we import the libraries. This causes issues for baking the visualization sets from the panel. Here is how you can recreate the issue.
1. Open Rhino and Pollination Panel.
2. Bake the visualization set for a study.
3. Open a new file.
4. Try to bake the visualization set in the new file.
You will get an error: Could not find Layer with ID 00000000-0000-0000-0000-000000000000
This is happening because when the code tries to look up the layers and create them the `doc` variable is still referring to the previous Rhino document which had the layer and is now closed. Since the older document already had this layer, Rhino doesn't create the new layer and then when it tries to bake the geometry to that layer it sees that the layer doesn't exist and …
> fix: remove cached version of the active doc

- ladybug_rhino/bakedisplay.py
- ladybug_rhino/text.py
It seems that the whole reason why I needed to add this mysterious factor in all of the text baking operations is because Rhino has this really annoying factor that scales all text in Model space, which was really hard to figure out. Now, I just disable it whenever we bake text and this always bakes the text correctly.
> fix(text): Finally fix the scaling issue when baking text

- ladybug_rhino/togeometry.py
I noticed that the Rhinocommon objects in the Rhino 8 cPython component don't use this Item property. Just sub-scripting directly seems to work on all platforms.
> fix(togeometry): Remove use of .NET Item for compatibility with cPython

- ladybug_rhino/command.py
Hi @chriswmackey, this pr fixes https://discourse.pollination.solutions/t/rhino-8-addtodoc-not-working-on-environmental-analysis-toolbar/3672/14
> fix(Rhino8): fix dll reference issue in Rhino 8 .NetCore
