ladybug_rhino/fromgeometry.py
This will be useful in workflows of coloring Model geometry with simulation results.
=> feat(fromgeometry): Add method to produce colored meshed from Face3D

ladybug_rhino/text.py, ladybug_rhino/togeometry.py, ladybug_rhino/viewport.py
This commit also includes a fix for the transform operation on text objects.
=> feat(viewport): Add a module for managing Rhino Viewports

ladybug_rhino/cli/__init__.py, ladybug_rhino/pythonpath.py
I also fixed some bugs with the Windows command.
=> fix(pythonpath): Change Mac command to just copy files to scripts

ladybug_rhino/grasshopper.py
I am starting to realize that a number of components will want to use this logic and having this method here will save us from writing 4 lines of code every time that we want to do it.
=> feat(grasshopper): Add method to apply longest list logic

ladybug_rhino/grasshopper.py, ladybug_rhino/viewport.py
These are to be used by the "View from Sun" component.  I am also adding some viewport functions that will strip out all of the Rhino-specific dependencies from the "Orient to Camera" component.
=> feat(viewport): Add methods to set viewport properties

ladybug_rhino/grasshopper.py
Similar to what legacy did with the cumulative sky matrix, this method can wrap large amounts of data so that it doesn't slow down the Grasshopper UI. However, this method is intended to be generic for many use cases and the objects can also be de-serialized such that users can get access to the detailed data if they want it.
Using this on the sun_is_visible output for some direct sunlight studies resulted in the run time dropping to 30% for an annual study.
=> feat(grasshopper): Add methods for wrapping data in Python objects

ladybug_rhino/intersect.py
Since all of the studies that need the vector angles to project results into the plane of a surface also need the check to eliminate vectors facing the wrong direction, this commit changes the intersect mesh/ray to also return the angles when normals are supplied.
=> fix(intersect): Implement more elegant way of returning vector angles

ladybug_rhino/bakegeometry.py, ladybug_rhino/baketext.py, ladybug_rhino/color.py, ladybug_rhino/colorize.py, ladybug_rhino/download.py, ladybug_rhino/fromgeometry.py, ladybug_rhino/planarize.py, ladybug_rhino/pythonpath.py, ladybug_rhino/text.py, ladybug_rhino/togeometry.py, ladybug_rhino/versioning/diff.py, ladybug_rhino/versioning/gather.py, ladybug_rhino/versioning/release.py
I am also cleaning up the import statements by separating the import of .Net stuff before trying to import Rhino, a Rhino Doc, or Grasshopper.
=> feat(versioning): Add module to help with releases

ladybug_rhino/grasshopper.py, ladybug_rhino/viewport.py
I also added some methods to bring components to the back or the front of the Grasshopper canvas.
=> feat(viewport): Add methods to capture view to file

ladybug_rhino/fromgeometry.py
I'm also cleaning up the code a little.
=> fix(fromgeometry): Trigger new release after last one failed

ladybug_rhino/cli/__init__.py, ladybug_rhino/ghpath.py, ladybug_rhino/pythonpath.py, ladybug_rhino/togeometry.py, tests/pythonpath_test.py
I think this should address all of the things that we will need for the executable installer.
Resolves https://github.com/ladybug-tools/ladybug-rhino/issues/131
=> feat(cli): Improve Python Search command and add GH copying command

ladybug_rhino/intersect.py
Resolves https://github.com/ladybug-tools/ladybug-rhino/issues/170
=> fix(intersect): Fix the recent change in RhinoCommon intersection return

docs/conf.py
Hi @chriswmackey,
Everything looks good on my side. Give it a look at in when you get a chance!
=> docs(cli): Improve CLI documentation structure

README.md, dev-requirements.txt, ladybug_rhino/cli/__init__.py, setup.py
The ladybug-core dependency already gives us click.
=> fix(deps): Remove unnecessary [cli] extra

ladybug_rhino/grasshopper.py, ladybug_rhino/intersect.py
=> Contain memory increase and avoid excessive dynamic method generation

.dependabot/config.yml, dev-requirements.txt, ladybug_rhino/grasshopper.py, ladybug_rhino/intersect.py
I'm also taking the opportunity to improve the docstrings, PEP8, and the docs/CI.
=> fix(intersect): Trigger a release with Giulio's improvement

ladybug_rhino/intersect.py
This commit changes the solid intersection method to use the same underlying method as Mingbo used here in IronBug:
https://github.com/MingboPeng/Ironbug/blob/master/src/Ironbug.LBHB_Legacy/Honeybee/Honeybee_IntersectMassII.cs
It seems there was a much more elegant way to do this in RhinoCommon and I just needed to be made aware of this ShrinkFaces method.
Now, the new intersection component should be as reliable as IronBug and run in roughly half the time.
=> fix(intersect): Implement better solid intersection method

ladybug_rhino/togeometry.py
This commit ensures that all of the information about the orientation of a planar Brep surface in Rhino is preserved when translating to ladybug_geometry.
This will be useful in workflows where one wants to ensure point grids are generated with a certain orientation or the up_vector of apertures conforms to what is seen in Rhino.
This change does not affect geometry translation from Meshes or curved Breps.
=> fix(togeometry): Preserve Plane orientation in translation if possible

ladybug_rhino/grasshopper.py, ladybug_rhino/intersect.py
This will make it easier to communicate certain messages to users and to set up parallel operations in a way that makes sense for the system running the calculation.
I'm also exposing a cpu_count option on the parallel solid intersection, which I plan to use in the Grasshopper plugin.
=> feat(grasshopper): Add methods for popups and recommended cpu count

ladybug_rhino/intersect.py
This changes the parallel input to be a specification of the cpu_count instead of an "all or nothing" type of situation.
=> fix(intersect): Add the ability to set CPU count on all intersections

ladybug_rhino/grasshopper.py
The function can automatically target a given number of CPUs and also runs it in single core using a preferred method.
=> feat(grasshopper): Add a method for running functions in parallel

ladybug_rhino/grasshopper.py, ladybug_rhino/intersect.py
This will be used to preserve path structures when deconstructing matrices.
=> fix(grasshopper): Add a method to merge data trees

ladybug_rhino/bakegeometry.py
Resolves https://github.com/ladybug-tools/ladybug-rhino/issues/238
=> fix(bakegeometry): Ensure that parent/child layers can be interpreted

ladybug_rhino/pythonpath.py
This should help correct some issues we created with past installers.
=> fix(pythonpath): Add a method to filter out duplicate search paths

ladybug_rhino/cli/__init__.py, ladybug_rhino/versioning/change.py, ladybug_rhino/versioning/userobject.py, requirements.txt
The new command allows people to change the installed version of Ladybug Tools. I have tested it and it appears to work.
I am also adding some changes to ensure that the current LB Versioner can handle updating components that live with the core ladybug_tools installation.
=> feat(cli): Add command to perform the Versioner task

ladybug_rhino/versioning/change.py
More info is here:
https://discourse.ladybug.tools/t/lbt-1-5-0-update-failed/19241/5
=> fix(change): Ensure reading the HTML does not cause failure

ladybug_rhino/togeometry.py
This way, I don't always have to convert a polycurve to a polyline.
=> fix(togeometry): Enable to_polygon2d to accept more data types
